In [2]:
import numpy as np

In [4]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
arr%2==0 # mask or boolean values with conditions # array supports vectorization (element wise operation)

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [10]:
arr[arr%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
arr[arr%5==0]

array([ 0,  5, 10, 15])

In [20]:
arr[(arr%2==0) & (arr%5==0)]

array([ 0, 10])

In [22]:
arr[(arr%2==0) | (arr%5==0)]

array([ 0,  2,  4,  5,  6,  8, 10, 12, 14, 15, 16, 18])

In [24]:
arr[(arr%2==0) ^ (arr%5==0)]

array([ 2,  4,  5,  6,  8, 12, 14, 15, 16, 18])

In [26]:
arr[(arr%2==0) & (arr%5==0)] = 100
arr

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [100,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [28]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
np.where(arr%2==0) # [(rows) (columns)]

(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3]), array([0, 2, 4, 1, 3, 0, 2, 4, 1, 3]))

In [34]:
x,y = np.where(arr%2==0) # [(rows) (columns)]
print(x)
print(y)

[0 0 0 1 1 2 2 2 3 3]
[0 2 4 1 3 0 2 4 1 3]


In [36]:
list(zip(x.tolist(),y.tolist()))

[(0, 0),
 (0, 2),
 (0, 4),
 (1, 1),
 (1, 3),
 (2, 0),
 (2, 2),
 (2, 4),
 (3, 1),
 (3, 3)]

In [38]:
np.where(arr%2==0,True,False)

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [40]:
np.where(arr%2==0,'Even','Odd')

array([['Even', 'Odd', 'Even', 'Odd', 'Even'],
       ['Odd', 'Even', 'Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even', 'Odd', 'Even'],
       ['Odd', 'Even', 'Odd', 'Even', 'Odd']], dtype='<U4')

### Create sub matrix from matrix

In [43]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
arr[0:2,1:3] # sub matrix with continuous values

array([[1, 2],
       [6, 7]])

In [ ]:
np.ix_() # Using `ix_` one can quickly construct index arrays that will index the cross product.

In [ ]:
np.ix_([rows],[columns])

In [51]:
np.ix_([0,1,2],[1,2,3])

(array([[0],
        [1],
        [2]]),
 array([[1, 2, 3]]))

In [57]:
arr[np.ix_([0,1,2],[0,2,1])] # sub matrix with non-continuous values

array([[ 0,  2,  1],
       [ 5,  7,  6],
       [10, 12, 11]])

In [59]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
arr[np.ix_([0,3],[3,2])]

array([[ 3,  2],
       [18, 17]])

In [63]:
arr[np.ix_([0,3],[1,2])]

array([[ 1,  2],
       [16, 17]])

### Vectorization & Broadcasting

- Vectorization is nothing but the element wise operation

- The numpy, It supports vectorization

- List does not support vectorization

In [1]:
l = [1,2,3]
l+5

TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as np

In [5]:
arr = np.array(l)
arr

array([1, 2, 3])

In [7]:
arr*5

array([ 5, 10, 15])

In [9]:
arr

array([1, 2, 3])

In [11]:
arr+5

array([6, 7, 8])

In [13]:
arr+arr

array([2, 4, 6])

In [15]:
l+l

[1, 2, 3, 1, 2, 3]

## Universal functions

- Arithmetic function

- Logical function

- Logarithm function

- Trigonometry function

- Exponent function

- Relational operator function

### Arithmetic function

In [20]:
arr

array([1, 2, 3])

In [28]:
np.add(1,45)

46

In [30]:
np.add(arr,5)

array([6, 7, 8])

In [32]:
np.subtract(arr,1)

array([0, 1, 2])

In [34]:
np.divide(arr,1)

array([1., 2., 3.])

In [36]:
np.multiply(arr,5)

array([ 5, 10, 15])

In [40]:
np.power(arr,3)

array([ 1,  8, 27])

In [42]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [44]:
np.square(arr)

array([1, 4, 9])

In [46]:
np.cumsum(arr)

array([1, 3, 6])

In [50]:
print(np.add(arr,6))
print(np.sqrt(arr))

[7 8 9]
[1.         1.41421356 1.73205081]


### Logical function

In [54]:
a = np.array([True,False,True,False])
b = np.array([False,True,False,True])

In [56]:
np.logical_and(a,b)

array([False, False, False, False])

In [58]:
np.logical_not(a,b)

array([False,  True, False,  True])

In [60]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [62]:
np.logical_xor(a,b)

array([ True,  True,  True,  True])

### Logarithm and Exponent functions

In [65]:
np.log(10)

2.302585092994046

In [67]:
np.log(100)

4.605170185988092

In [69]:
np.log(5)

1.6094379124341003

In [71]:
np.log(2)

0.6931471805599453

In [73]:
np.log(3)

1.0986122886681098

In [75]:
np.log(5)/np.log(10)

0.6989700043360187

In [77]:
np.log10(5)

0.6989700043360189

In [81]:
np.log1p(2)

1.0986122886681098

In [83]:
np.log2(8)

3.0

In [87]:
np.logaddexp(arr,5)

array([5.01814993, 5.04858735, 5.12692801])

In [89]:
np.logaddexp2(arr,10)

array([10.00281502, 10.00562455, 10.01122726])

In [94]:
np.exp(5)

148.4131591025766

In [96]:
np.exp2(5)

32.0

In [102]:
print(np.expm1(10))

print(np.exp(10)-1)

22025.465794806718
22025.465794806718


### Trigonometry function

In [107]:
np.pi

3.141592653589793

In [109]:
np.sin(90)

0.8939966636005579

In [113]:
np.sin(np.deg2rad(90))

1.0

In [117]:
np.sin(np.rad2deg(90))

-0.9540914674728181

In [121]:
print(np.sin(np.deg2rad(90)))

print(np.deg2rad(90))

print(np.rad2deg(90))

1.0
1.5707963267948966
5156.620156177409


In [123]:
np.cos(90)

-0.4480736161291702

In [125]:
np.cos(np.rad2deg(90))

-0.2995153947555356

In [127]:
np.cos(np.rad2deg(0))

1.0

In [129]:
np.cos(np.rad2deg(45))

-0.5918127259718502

In [131]:
np.cos(np.deg2rad(45))

0.7071067811865476

In [133]:
np.sinh(np.deg2rad(90))

2.3012989023072947

In [137]:
np.sinh(np.deg2rad(45))

0.8686709614860095

In [139]:
np.sinh(np.deg2rad(60))

1.2493670505239751

In [141]:
np.cosh(90)

6.102016471589204e+38

In [143]:
np.sinh(90)

6.102016471589204e+38

In [149]:
np.arcsin(1)

1.5707963267948966

In [151]:
np.arcsinh(90)

5.192987713658941

In [153]:
8 > 6

True

### Relational operator function

In [156]:
8 > 6

True

In [158]:
6<7

True

In [160]:
7 > 11

False

In [162]:
5 == 5

True

In [164]:
6!=5

True

In [166]:
5!=5

False

In [168]:
5 >= 3

True

In [170]:
3 <= 5

True

In [172]:
5>=6

False

In [174]:
5<=4

False