**Broadcasting**

- the process of arithmetic operation in different shape

- Rules :

- the both arays are compatible :-

    - if the both arrays are same shape

    - Any one has one value

- (7,3)+(7,3) # True

- (7,3)+(1,1) # True

- (3,2)+(2,3) # False


In [10]:
import numpy as np

a = np.array([[4,5,6],[1,2,3]])
b = np.array([[4,5,6],[1,2,3]])
a.shape, b.shape

((2, 3), (2, 3))

In [12]:
a+b

array([[ 8, 10, 12],
       [ 2,  4,  6]])

In [14]:
a = np.array([[4,5,6],[1,2,3]])
b = np.array([[4,5],[1,2],[7,8]])
a.shape, b.shape

((2, 3), (3, 2))

In [16]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [22]:
a = np.array([[4,5,6],[1,2,3]])
b = np.array([[4]])
a.shape, b.shape

((2, 3), (1, 1))

In [24]:
a+b

array([[ 8,  9, 10],
       [ 5,  6,  7]])

In [26]:
a = np.array([[4,5,6],[1,2,3]])
b = np.array([[1,2,3]])
a.shape, b.shape

((2, 3), (1, 3))

In [28]:
a+b

array([[5, 7, 9],
       [2, 4, 6]])

In [32]:
a = np.arange(12).reshape(3,4)
b = np.arange(10,22).reshape(3,4)

a+b

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [34]:
a = np.arange(12).reshape(3,4)
b = np.arange(10,22).reshape(4,3)

a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

**Note** : a=(4,3), b=(3,4), When you compare coresponding values from left to right (x1)4 != (x2)3 and (y1)3 != (y2)4

In [38]:
a = np.arange(1).reshape(1,1)
b = np.arange(1).reshape(1,1)

a+b

array([[0]])

In [40]:
x = np.array([7,4,45,1])
y = np.array([1,2,3,5])
x.shape,y.shape

((4,), (4,))

In [42]:
x+y

array([ 8,  6, 48,  6])

In [44]:
z = np.array([[1,2,4,8],[2,5,7,9]])
z.shape

(2, 4)

In [46]:
x+z

array([[ 8,  6, 49,  9],
       [ 9,  9, 52, 10]])

In [ ]:
x # (1,4)
y # (1,4)
z # (2,4)

In [50]:
s = np.arange(12).reshape(3,2,2)
s

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [58]:
p = np.array([1,2,3])
p.shape # (1,3)

(3,)

In [56]:
s+p

ValueError: operands could not be broadcast together with shapes (3,2,2) (3,) 

In [62]:
s = np.arange(12).reshape(3,2,2)
p = np.arange(6).reshape(3,1,2)

s+p

array([[[ 0,  2],
        [ 2,  4]],

       [[ 6,  8],
        [ 8, 10]],

       [[12, 14],
        [14, 16]]])

In [64]:
p

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [66]:
s = np.arange(12).reshape(3,2,2)
p = np.arange(6).reshape(3,2)

s+p

ValueError: operands could not be broadcast together with shapes (3,2,2) (3,2) 

In [68]:
s = np.arange(12).reshape(3,2,2)
p = np.arange(6).reshape(3,2,1)

s+p

array([[[ 0,  1],
        [ 3,  4]],

       [[ 6,  7],
        [ 9, 10]],

       [[12, 13],
        [15, 16]]])

In [70]:
s = np.arange(12).reshape(3,2,2)
p = np.arange(2).reshape(1,2,1)

s+p

array([[[ 0,  1],
        [ 3,  4]],

       [[ 4,  5],
        [ 7,  8]],

       [[ 8,  9],
        [11, 12]]])

**resize**

- change the size of the array

- Return a new array with the specified shape.

- reshape does not take any duplicates

- resize takes duplicates when size is much longer than the array

In [75]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [79]:
np.resize(a,(2,4))

array([[1, 2, 3, 4],
       [5, 1, 2, 3]])

In [83]:
import math

math.sqrt(4)

2.0

In [91]:
math.sqrt(4,9)

TypeError: math.sqrt() takes exactly one argument (2 given)

In [87]:
np.sqrt([4,9])

array([2., 3.])

In [93]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])