In [2]:
import numpy as np

In [4]:
mean = np.array([7,8,9,4,5,6])
np.mean(mean)

6.5

In [6]:
std = np.array([7,8,9,4,5,6])
np.std(std)

1.707825127659933

In [8]:
var = np.array([7,8,9,4,5,6])
np.var(var)

2.9166666666666665

In [12]:
a = np.array([7,8,9,4,5,6])
a

array([7, 8, 9, 4, 5, 6])

Data Cleaning
-------------

- Remove unwanted values

- to remove duplicates values

- to remove null values

- to maintain null values with aggregation values

- to remove infinity(positive/negative) values

In [15]:
import numpy as np

arr = np.array([4, 5,np.nan, np.nan, np.inf, 9, 6])
arr

array([ 4.,  5., nan, nan, inf,  9.,  6.])

In [17]:
arr.astype('<U')

array(['4.0', '5.0', 'nan', 'nan', 'inf', '9.0', '6.0'], dtype='<U32')

In [19]:
arr.astype('int')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_28398/3414054417.py:1: RuntimeWarning: invalid value encountered in cast
  arr.astype('int')


array([                  4,                   5,                   0,
                         0, 9223372036854775807,                   9,
                         6])

In [23]:
import numpy as np

arr = np.array([4, 5,np.nan, np.nan, np.inf, -np.inf, 9, 6])
arr.astype('int')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_28398/1503402420.py:4: RuntimeWarning: invalid value encountered in cast
  arr.astype('int')


array([                   4,                    5,                    0,
                          0,  9223372036854775807, -9223372036854775808,
                          9,                    6])

In [25]:
import numpy as np

arr = np.array([4, 5,np.nan, np.nan, np.inf, -np.inf, 9, 6])
arr.astype('bool')

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [27]:
arr.astype('complex')

array([  4.+0.j,   5.+0.j,  nan+0.j,  nan+0.j,  inf+0.j, -inf+0.j,
         9.+0.j,   6.+0.j])

In [35]:
a = 4 + 5j # real + imag & j = sqrt(-1)

complex(a)

(4+5j)

In [37]:
c = complex(8,9)
c

(8+9j)

In [41]:
c.real

8.0

In [43]:
arr

array([  4.,   5.,  nan,  nan,  inf, -inf,   9.,   6.])

In [49]:
print("Array :",arr)
np.isnan(arr)

Array : [  4.   5.  nan  nan  inf -inf   9.   6.]


array([False, False,  True,  True, False, False, False, False])

In [51]:
arr[np.isnan(arr)]

array([nan, nan])

In [53]:
inf_value = np.isinf(arr)
inf_value

array([False, False, False, False,  True,  True, False, False])

In [55]:
arr[inf_value]

array([ inf, -inf])

In [57]:
np.isposinf(arr)

array([False, False, False, False,  True, False, False, False])

In [59]:
arr[np.isposinf(arr)]

array([inf])

In [61]:
np.isneginf(arr)

array([False, False, False, False, False,  True, False, False])

In [63]:
arr[np.isneginf(arr)]

array([-inf])

In [65]:
import numpy as np

arr = np.array([4, 5,np.nan, np.nan, np.inf, -np.inf, 9, 6])
arr

array([  4.,   5.,  nan,  nan,  inf, -inf,   9.,   6.])

In [67]:
~np.isnan(arr)

array([ True,  True, False, False,  True,  True,  True,  True])

In [71]:
arr1 = arr[~np.isnan(arr)]
arr1

array([  4.,   5.,  inf, -inf,   9.,   6.])

In [73]:
np.isinf(arr1)

array([False, False,  True,  True, False, False])

In [75]:
arr1[np.isinf(arr1)]

array([ inf, -inf])

In [77]:
arr1[~np.isinf(arr1)]

array([4., 5., 9., 6.])

In [79]:
arr2 = arr1[~np.isinf(arr1)]
arr2

array([4., 5., 9., 6.])

In [83]:
import numpy as np

arr = np.array([4, 5,np.nan, np.inf, -np.inf, 9, 6])
arr

array([  4.,   5.,  nan,  inf, -inf,   9.,   6.])

In [85]:
np.nan_to_num(arr)

array([ 4.00000000e+000,  5.00000000e+000,  0.00000000e+000,
        1.79769313e+308, -1.79769313e+308,  9.00000000e+000,
        6.00000000e+000])

In [91]:
np.nan_to_num(arr,nan=6.5,posinf=100)

array([ 4.00000000e+000,  5.00000000e+000,  6.50000000e+000,
        1.00000000e+002, -1.79769313e+308,  9.00000000e+000,
        6.00000000e+000])

In [93]:
np.nan_to_num(arr,nan=6.5,posinf=100).astype('int')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_28398/634070956.py:1: RuntimeWarning: invalid value encountered in cast
  np.nan_to_num(arr,nan=6.5,posinf=100).astype('int')


array([                   4,                    5,                    6,
                        100, -9223372036854775808,                    9,
                          6])

In [95]:
np.nan_to_num(arr,nan=6.5,posinf=100,neginf=150).astype('int')

array([  4,   5,   6, 100, 150,   9,   6])

How to create array with null values
-----------

In [97]:
arr = np.array([[7,np.nan,8,np.inf],[10,np.inf,4,9]])
arr

array([[ 7., nan,  8., inf],
       [10., inf,  4.,  9.]])

To return boolean index / mask
--------

In [ ]:
# np.isnan(arr)
# np.isposinf(arr)
# np.isneginf(arr)

In [107]:
print("NaN values :",np.isnan(arr))
print()
print("Positive inf. :",np.isposinf(arr))
print()
print("Negative inf. :",np.isneginf(arr))
print()

NaN values : [[False  True False False]
 [False False False False]]

Positive inf. : [[False False False  True]
 [False  True False False]]

Negative inf. : [[False False False False]
 [False False False False]]



To return True values
------------

In [110]:
print("NaN values :",arr[np.isnan(arr)])
print()
print("Positive inf. :",arr[np.isposinf(arr)])
print()
print("Negative inf. :",arr[np.isneginf(arr)])
print()

NaN values : [nan]

Positive inf. : [inf inf]

Negative inf. : []



Cleaning / Removing the Null values
----

In [123]:
arr1 = arr[~np.isnan(arr)]
arr1

array([ 7.,  8., inf, 10., inf,  4.,  9.])

In [129]:
arr2 = arr1[~np.isinf(arr1)]
arr2

array([ 7.,  8., 10.,  4.,  9.])