Linear Algebra
--------------

- Dot product, matrix multiplication
        
- Determinant, inverse, eigenvalues/eigenvectors (np.linalg)

- Solving linear equations (np.linalg.solve)

In [3]:
import numpy as np

arr=np.array([7,8,9]) 

arr1=np.array([1,2,3]) 

arr2=np.array([[7,5,6],
               [1,2,3]]) 

np.multiply(arr,arr1)

array([ 7, 16, 27])

Matrix with Different Shapes
----------------------------
vector <-> vector => scaler

## Note: The dot product always use in between two vectors and return scaler values

vector <-> matrix  => vector(scaler) / 1D array

matrix <-> matrix => matrix

## Note : it should contain column of the first matrix equal to row  of the second matrix.

In [10]:
np.dot(arr,arr1)

50

In [12]:
arr@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [14]:
np.matmul(arr,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [16]:
x=np.arange(12).reshape(3,4)
y=np.arange(8).reshape(4,2)

In [18]:
np.dot(x,y)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [20]:
np.matmul(x,y)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [24]:
a=np.array([7,8,9])
b=np.array([[4],
            [8],
            [6]])

np.matmul(a,b)

array([146])

In [26]:
np.dot(a,b)

array([146])

In [28]:
a@b

array([146])

In [30]:
x=np.array([[7,8,9],
            [1,2,3],
            [4,6,8]])

In [34]:
np.trace(x) # Sum of diagonal values

17

In [36]:
np.linalg.matrix_rank(x)

2

In [38]:
np.linalg.det(x)

-2.03012210217171e-15

In [40]:
np.linalg.inv(x)

# if the matrix det==0 then the inverse not applicable.

array([[ 9.85162418e+14,  4.92581209e+15, -2.95548726e+15],
       [-1.97032484e+15, -9.85162418e+15,  5.91097451e+15],
       [ 9.85162418e+14,  4.92581209e+15, -2.95548726e+15]])

In [42]:
x=np.array([[7,8,9],
            [1,2,3],
            [4,10,8]])

np.trace(x)

17

In [44]:
np.linalg.det(x)

-47.999999999999986

In [46]:
np.linalg.inv(x)

array([[ 0.29166667, -0.54166667, -0.125     ],
       [-0.08333333, -0.41666667,  0.25      ],
       [-0.04166667,  0.79166667, -0.125     ]])

In [48]:
x=np.array([[7,8,9],
            [1,2,3],
            ])

np.trace(x)

9

In [50]:
np.linalg.det(x) 
# The dot value always applicable on square matrix.

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
# 2x+y=12

# 3x+2y=15

In [52]:
x=np.array([[2,1],
   [3,2]])
y=np.array([12,15])

np.linalg.solve(x,y)

array([ 9., -6.])

In [54]:
np.linalg.eigvals(x)

array([3.73205081, 0.26794919])

In [56]:
np.linalg.eig(x)

EigResult(eigenvalues=array([3.73205081, 0.26794919]), eigenvectors=array([[ 0.5      , -0.5      ],
       [ 0.8660254,  0.8660254]]))

In [58]:
data={
    'name':['meena','rakesh','leeladas'],
    'ages':[28,29,27],
}

In [60]:
import pandas as pd

# Series -> means vector /1-d array
# DateFrame -> 2d /matrix/tabular

In [62]:
df=pd.DataFrame(data,index=['a','b','c'])

- loc -> label

- iloc -> integer label

In [65]:
df

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27

In [67]:
df[['name','ages']]

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27

In [69]:
df.iloc[2]

name    leeladas
ages          27
Name: c, dtype: object

In [71]:
df

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27

In [73]:
df.loc['b']

name    rakesh
ages        29
Name: b, dtype: object

In [75]:
df.iloc[1]

name    rakesh
ages        29
Name: b, dtype: object

In [77]:
df.loc['d']=['radha',30]

In [79]:
df

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27
d     radha    30

In [81]:
df.drop('d',axis=0)

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27

In [83]:
df.loc['c']

name    leeladas
ages          27
Name: c, dtype: object

In [85]:
df

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27
d     radha    30

In [87]:
df.iloc[1:3,1]

b    29
c    27
Name: ages, dtype: int64

In [89]:
df.loc[:,'name':'ages']

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27
d     radha    30

In [91]:
df.iloc[:,:2]

name  ages
a     meena    28
b    rakesh    29
c  leeladas    27
d     radha    30