In [2]:
import numpy as np

arr=np.arange(0,28)
arr # 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [4]:
print(arr.reshape(4,7)) # rows=4 ,columns=7

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [6]:
print(arr1:=arr.reshape(7,4)) # rows=7 ,columns=4

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [8]:
print(arr.reshape(1,28)) # rows=1 ,columns=28

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27]]


In [10]:
print(arr.reshape(28,1)) # rows=28 ,columns=1

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]]


In [12]:
print(arr.reshape(-1)) # return flat array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [14]:
lst=[[7,8,9],[4,5,6]]
lst1=np.array(lst)
lst1

array([[7, 8, 9],
       [4, 5, 6]])

In [16]:
list(lst1.reshape(-1).tolist())

[7, 8, 9, 4, 5, 6]

In [18]:
lst=[[7,8,9],[4,5,6]]
result=[]
for i in lst:
    for j in i:
        result.append(j)
result

[7, 8, 9, 4, 5, 6]

In [20]:
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr1=np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### What is the difference between reshape, ravel, flatten

- **reshape** => Returns an array containing the same data with a new shape, but this is the view

- **ravel** => Return a flattened array and this is also view

- **flatten** => Return a copy of the array collapsed into one dimension.

In [32]:
arr1=np.array([[7,4,6],[1,2,3]])

In [34]:
arr1

array([[7, 4, 6],
       [1, 2, 3]])

In [36]:
# reshape

res=arr1.reshape(-1)
res[0]=100
print(res)
print(arr1)

[100   4   6   1   2   3]
[[100   4   6]
 [  1   2   3]]


In [38]:
# ravel 

rav=arr1.ravel()
rav[1]=120
print(arr1)
print(rav)

[[100 120   6]
 [  1   2   3]]
[100 120   6   1   2   3]


In [40]:
# flatten

flat=arr1.flatten()
flat[1]=50
print(arr1)
print(flat)

[[100 120   6]
 [  1   2   3]]
[100  50   6   1   2   3]


In [42]:
arr1

array([[100, 120,   6],
       [  1,   2,   3]])

### Index and Slicing

In [45]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**Index** => Index means position of the value. The position of starting is from 0.

In [51]:
arr[0]

array([0, 1, 2])

In [53]:
lst=[[7,8,9],[4,5,6]]
lst[0]

[7, 8, 9]

In [55]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
arr[2]

array([6, 7, 8])

In [59]:
arr[0][2]

2

In [61]:
arr[[0,1]] # Multi index calling.

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
arr[[0,1,2,3]]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
print(arr[2][2])

8


**Slicing**

- **Positive direction** (Forward direction) : 0....n-1

- **Negative direction** (Backward direction) : -1......n

In [74]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
arr[:2,1:3]

array([[1, 2],
       [4, 5]])

In [80]:
arr[0:4:3]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [82]:
temps = np.array([32, 35, 31, 30, 29, 28, 33])
temps

array([32, 35, 31, 30, 29, 28, 33])

In [84]:
# 1. Get the temperature on Day 1 and Day 7.
temps[[0,6]]

array([32, 33])

In [86]:
# 2. Get the last 3 days’ temperatures
temps[-3:]

array([29, 28, 33])

In [124]:
# 3. Get Day 2 to Day 5 temperatures.
    
temps[1:-2]

array([35, 31, 30, 29])

In [126]:
# 4. Reverse the week’s data.
    
temps[::-1]

array([33, 28, 29, 30, 31, 35, 32])

In [128]:
# 5. Get every alternate day’s temperature.

temps[::2]

array([32, 31, 29, 33])

In [92]:
temps[2:-2:-1]

array([], dtype=int64)

In [94]:
[i for i in range(1,10)] # 0,...10

# step =1 , start<stop
           # 0<10

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [96]:
[i for i in range(10,1)] # 0,...10

# step =1 , start<stop
           # 10<1 # wrong

[]

In [98]:
[i for i in range(10,1,-1)] # 0,...10

# step =-1 , start>stop
           # 10>1 # CORRECT

[10, 9, 8, 7, 6, 5, 4, 3, 2]

In [100]:
[i for i in range(1,10,-1)] # 0,...10

# step =-1 , start>stop
           # 1>10 # wrong

[]

In [102]:
temps

array([32, 35, 31, 30, 29, 28, 33])

In [104]:
temps[:-3] # step =1 ,start=0 ,stop=4

array([32, 35, 31, 30])

In [106]:
temps[-3:] # step =1,start=-3,stop

array([29, 28, 33])

In [108]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [110]:
np.random.permutation(arr) # copy

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [112]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [116]:
np.random.shuffle(arr) # view

In [118]:
arr

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [120]:
# choice(a, size=None, replace=True, p=None)

np.random.choice([7,8,9,4,5,6],2,replace=False,p=[0.6,0.2,0.2,0,0,0])

array([7, 9])