In [2]:
import numpy as np

**Functions**

In [ ]:
np.eye()

In [ ]:
np.identity()

In [ ]:
np.ones()

In [ ]:
np.zeros()

In [ ]:
np.arange(start,stop,step)

In [ ]:
np.linspace()

In [ ]:
np.full()

In [ ]:
np.fill_diagonal()

In [ ]:
np.empty()

In [4]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
np.eye(4,3,1,dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.eye(4,5,3,dtype=int)

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.eye(4,5,3,dtype=bool)

array([[False, False, False,  True, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [16]:
np.eye(4,5,3,dtype=str)

array([['', '', '', '1', ''],
       ['', '', '', '', '1'],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
np.identity(4,dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [24]:
np.identity(4,dtype='int64')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
np.linspace(4,6,retstep=True)

(array([4.        , 4.04081633, 4.08163265, 4.12244898, 4.16326531,
        4.20408163, 4.24489796, 4.28571429, 4.32653061, 4.36734694,
        4.40816327, 4.44897959, 4.48979592, 4.53061224, 4.57142857,
        4.6122449 , 4.65306122, 4.69387755, 4.73469388, 4.7755102 ,
        4.81632653, 4.85714286, 4.89795918, 4.93877551, 4.97959184,
        5.02040816, 5.06122449, 5.10204082, 5.14285714, 5.18367347,
        5.2244898 , 5.26530612, 5.30612245, 5.34693878, 5.3877551 ,
        5.42857143, 5.46938776, 5.51020408, 5.55102041, 5.59183673,
        5.63265306, 5.67346939, 5.71428571, 5.75510204, 5.79591837,
        5.83673469, 5.87755102, 5.91836735, 5.95918367, 6.        ]),
 np.float64(0.04081632653061224))

In [42]:
np.linspace(4,6,retstep=True,50)

SyntaxError: positional argument follows keyword argument (749184838.py, line 1)

In [52]:
np.linspace(4,6,retstep=True,dtype=int)

(array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 6]),
 np.float64(0.04081632653061224))

In [54]:
np.linspace(4,6,retstep=True,num=10,endpoint=False)

(array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8]), np.float64(0.2))

In [58]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [64]:
print(np.arange(4))

print(np.arange(0,4))

print(np.arange(0,4,1))

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]


In [90]:
a = np.array([[1,2,3],[6,7,8]])
np.fill_diagonal(a,2)
a

array([[2, 2, 3],
       [6, 2, 8]])

In [76]:
np.arange(20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [78]:
np.full((4,3),0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
np.full((4,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [82]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.empty(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
np.empty(4)

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323])

**Random Functions**

In [ ]:
import numpy as np

from numpy import random

In [ ]:
np.random.rand()

np.random.randint()

np.random.randn()

np.random.random()

np.random.random_sample()

np.random.uniform()

np.random.normal()

np.random.permutation()

np.random.choice()

In [94]:
np.random.rand()

0.05103506513699729

In [96]:
np.random.rand(5)

array([0.74746482, 0.22899223, 0.24915863, 0.37956119, 0.22115241])

In [107]:
np.random.rand(4,2,3)

array([[[0.80276516, 0.73923905, 0.47564194],
        [0.65281306, 0.16733848, 0.52412999]],

       [[0.80735615, 0.10193975, 0.91228024],
        [0.09853338, 0.13056473, 0.90014093]],

       [[0.64925676, 0.97382486, 0.61275145],
        [0.9683358 , 0.32516053, 0.60584713]],

       [[0.24314481, 0.97900163, 0.8303117 ],
        [0.1863434 , 0.96473471, 0.79313529]]])

In [98]:
np.random.randn()

-1.008499658779526

In [100]:
np.random.randn(5)

array([-1.09038571,  2.87763326,  0.27171208,  0.46719018,  0.01992454])

In [109]:
np.random.randn(2,3,4)

array([[[-1.35623552,  1.05326944,  2.12882305,  0.02897433],
        [-1.10512041,  0.69183123,  1.39767714, -0.31439268],
        [ 2.01973734, -0.07131662,  0.72448013, -1.19495929]],

       [[ 0.7850319 , -1.76179225,  2.2001263 , -0.17955042],
        [ 0.46171108,  0.32556526, -1.35942904,  0.86658197],
        [-0.20716918, -1.32405644, -1.26456502, -2.61810416]]])

In [113]:
# Return random floats in the half-open interval [0.0, 1.0).

np.random.random()

0.37889342797735537

In [117]:
np.random.random((4,8))

array([[0.78563188, 0.18655734, 0.77242465, 0.46167636, 0.48066138,
        0.63624085, 0.2048453 , 0.34837952],
       [0.26367351, 0.20527206, 0.29654517, 0.10964709, 0.20472979,
        0.02381867, 0.49977051, 0.31741393],
       [0.59748145, 0.39140025, 0.55201687, 0.43476476, 0.40833554,
        0.51326821, 0.9584296 , 0.35276179],
       [0.80665798, 0.9559169 , 0.10121977, 0.64036282, 0.49251303,
        0.45466717, 0.10800063, 0.92843962]])

In [119]:
np.random.randint(4,8)

7

In [125]:
np.random.randint(4,8,4)

array([5, 7, 6, 7])

In [127]:
np.random.random_integers(1,2)

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_44459/1304852787.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  np.random.random_integers(1,2)


np.int64(1)

In [129]:
np.random.random_sample()

0.7031148525569834

In [133]:
np.random.random_sample(5)

array([0.3585364 , 0.9707718 , 0.34271391, 0.76493562, 0.30318679])

In [135]:
np.random.uniform()

0.8770407428700836

In [141]:
np.random.uniform(1,5)

2.929141778613931

In [139]:
np.random.uniform(2,5,2)

array([2.47800636, 3.76112617])

In [143]:
np.random.uniform(1,2,10)

array([1.30590482, 1.33841102, 1.04017786, 1.59446014, 1.29435411,
       1.59005431, 1.61208998, 1.41569515, 1.06852421, 1.19715564])

In [145]:
np.random.normal()

-1.3473623903934977

In [149]:
np.random.normal(4,5)

3.3464278836353523

In [155]:
np.random.permutation(5)

array([0, 4, 1, 3, 2])

In [165]:
x = np.array([[1,2,3],[4,5,6]])
np.random.permutation(x)

array([[4, 5, 6],
       [1, 2, 3]])

In [171]:
x = np.array( [1,2,3,4,5,6])
np.random.permutation(x)

array([4, 1, 5, 3, 6, 2])

In [173]:
y=np.arange(20).reshape(10,2)
np.random.permutation(y)

array([[14, 15],
       [ 2,  3],
       [16, 17],
       [10, 11],
       [ 6,  7],
       [ 4,  5],
       [ 0,  1],
       [ 8,  9],
       [18, 19],
       [12, 13]])

In [181]:
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
a

array([5, 2, 4, 3, 1])