In [2]:
import numpy as np

**Difference between Index and Multi (Fancy) Index**

**Index** :
- It returns only one position
- Index always return specific position value
- By using of index we can update the value

**Multi Index** : 
- It returns number of positions
- It returns specific number of positions
- By using of multi index we can update multiple values

In [4]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
arr[2]

array([ 8,  9, 10, 11])

In [8]:
arr[0][2]

2

In [10]:
arr[0,2]

2

In [12]:
l = [1,2,3,4,5]
l[0] = 50
l

[50, 2, 3, 4, 5]

In [18]:
arr[[0,2],[3,1]]=20,30
arr

array([[ 0,  1,  2, 20],
       [ 4,  5,  6,  7],
       [ 8, 30, 10, 11],
       [12, 13, 14, 15]])

In [20]:
arr[0,2:4]

array([ 2, 20])

In [22]:
arr[0,2:4]=100
arr

array([[  0,   1, 100, 100],
       [  4,   5,   6,   7],
       [  8,  30,  10,  11],
       [ 12,  13,  14,  15]])

In [27]:
arr[[2,3],[2,3]] # points (2,2) & (3,3)

array([10, 15])

In [31]:
arr[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [35]:
arr[1:3,2:4]=150
arr

array([[  0,   1, 100, 100],
       [  4,   5, 150, 150],
       [  8,  30, 150, 150],
       [ 12,  13,  14,  15]])

In [41]:
arr[1:3,2:4]=150,250
arr

array([[  0,   1, 100, 100],
       [  4,   5, 150, 250],
       [  8,  30, 150, 250],
       [ 12,  13,  14,  15]])

**3D Array**

In [46]:
arr = np.arange(30).reshape(2,3,5) # depth (no of 2d), rows, columns
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [48]:
arr[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
arr[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [52]:
len(arr)

2

In [54]:
arr[0:2]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [56]:
arr[[0],[1]]

array([[5, 6, 7, 8, 9]])

In [58]:
arr[[0],[1],[2]]

array([7])

In [60]:
arr[0][1][2]

7

In [62]:
arr_2 = np.arange(12).reshape(4,3)
arr_2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
arr_2[0][2]

2

In [72]:
arr_2[[0],[2]]

array([2])

**Boolean Index**

- index : it returns specific values with those positions

- boolean : return values with those booleans

In [77]:
arr = np.array([1,2,3,4,5])

arr[[True,False,True,False,True]]

array([1, 3, 5])

In [85]:
res = arr%2 == 0
print(arr[res])

[2 4]


In [87]:
arr%2 == 0

array([False,  True, False,  True, False])

In [91]:
arr[arr%2==0] #arr[mask] --> return values

array([2, 4])

In [93]:
arr1 = np.arange(10,50,2).reshape(4,5)
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [97]:
# mask = condition

mask = arr1%5==0
arr1[mask]

array([10, 20, 30, 40])

In [99]:
lst = [7,8,9,45]
lst%2==0

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [101]:
mask = arr1%5==0
arr1[mask]

array([10, 20, 30, 40])