### Concatenation

- Join number of arrays along with existing axis(0,1)

In [4]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [8]:
b = np.array([5,2,8,3])
b.shape

(4,)

In [12]:
a+b # vectorization with broadcasting rules

array([ 6,  4, 11,  7])

In [22]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

In [24]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 2, 8, 3])

In [26]:
np.concatenate((a,b),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [28]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[2,3,5,6]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [2, 3, 5, 6]])

In [30]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[2,3,5,6]])
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 2, 3, 5, 6]])

In [32]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[2,3,5,6]])
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [34]:
a = np.array([[1,2,3,4]])
b = np.array([[1,2,3,4],[2,3,5,6]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 5, 6]])

In [36]:
a = np.array([[1,2,3,4]])
b = np.array([[1,2,3,4],[2,3,5,6]])
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [42]:
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)
np.concatenate((a,b),axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [44]:
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [48]:
a = np.arange(12).reshape(4,3)
b = np.arange(9).reshape(3,3)
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [50]:
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)
np.concatenate((a,b),axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [54]:
a = np.arange(12).reshape(3,4)
b = np.arange(15).reshape(3,5)
np.concatenate((a,b),axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [56]:
a = np.arange(12).reshape(3,4)
b = np.arange(15).reshape(3,5)
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [58]:
a = np.arange(12).reshape(3,4)
b = np.arange(4).reshape(1,4)
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [60]:
a = np.arange(12).reshape(3,4)
b = np.arange(4).reshape(1,4)
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

hstack
------

- Stack arrays in sequence horizontally (column wise).

In [66]:
a = np.arange(12).reshape(3,4)
b = np.arange(9).reshape(3,3)

np.hstack((a,b))

array([[ 0,  1,  2,  3,  0,  1,  2],
       [ 4,  5,  6,  7,  3,  4,  5],
       [ 8,  9, 10, 11,  6,  7,  8]])

vstack
------

- Stack arrays in sequence vertically (row wise).

In [68]:
a = np.arange(12).reshape(3,4)
b = np.arange(4).reshape(1,4)

np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

split
-----

- divide array into number of equal sizes sub-array

In [84]:
a = np.arange(12).reshape(3,4)

np.split(a,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [86]:
a = np.arange(12).reshape(3,4)

np.split(a,2,axis=0)

ValueError: array split does not result in an equal division

In [88]:
a = np.arange(16).reshape(4,4)

np.split(a,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [90]:
a = np.arange(16).reshape(4,4)

np.split(a,4,axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

array_split
-----------

- divide the array into unequal size sub-array

In [93]:
a = np.arange(16).reshape(4,4)

np.array_split(a,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [95]:
a = np.arange(12).reshape(3,4)

np.array_split(a,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

### Reduction & Statistics

In [99]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [101]:
np.sum(a)

10

In [103]:
np.sum(a,axis=0)

10

In [109]:
a.dtype

dtype('int64')

In [111]:
a.astype('float')

array([1., 2., 3., 4.])

In [113]:
a.astype('int')

array([1, 2, 3, 4])

In [115]:
np.sum((a,b))

36

In [117]:
np.sum(b)

26

In [119]:
np.max(a)

4

In [121]:
np.max(b)

8

In [125]:
np.max((a,b))

8

In [127]:
a.max()

4

In [129]:
b.max()

8

In [131]:
((a,b)).max()

AttributeError: 'tuple' object has no attribute 'max'

In [133]:
np.max((a,b))

8

In [135]:
a = np.array([[1,5],[9,8]])

np.max(a,axis=0)

array([9, 8])

In [137]:
np.max(a,axis=1)

array([5, 9])

In [139]:
a = np.array([[1,5],[9,2]])

np.max(a,axis=0)

array([9, 5])

In [141]:
a = np.array([[1,5],[9,2]])

np.max(a,axis=1)

array([5, 9])

In [143]:
a = np.array([[1,5],[9,2]])

np.min(a,axis=0)

array([1, 2])

In [145]:
a = np.array([[1,5],[9,2]])

np.min(a,axis=1)

array([1, 2])

In [147]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [149]:
np.min(a)

1

In [151]:
np.min(b)

5

In [153]:
np.mean(a)

2.5

In [155]:
np.mean(b)

6.5

In [157]:
np.std(a)

1.118033988749895

In [159]:
np.std(b)

1.118033988749895

In [161]:
np.var(a)

1.25

In [163]:
np.var(b)

1.25

In [173]:
np.argmax(a) #Returns the indices of the maximum values along an axis.

3

In [167]:
np.argmax(b)

3

In [175]:
np.argmin(a) # Returns the indices of the minimum values along an axis.

0

In [171]:
np.argmin(b)

0

In [177]:
np.mean((a,b))

4.5

In [179]:
np.std((a,b))

2.29128784747792

In [181]:
np.var((a,b))

5.25

In [183]:
np.argmax((a,b))

7

In [185]:
np.argmin((a,b))

0

In [187]:
c = np.arange(24).reshape(3,2,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [189]:
np.sum(c)

276

In [191]:
np.sum(c,axis=0)

array([[24, 27, 30, 33],
       [36, 39, 42, 45]])

In [193]:
np.sum(c,axis=1)

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42]])

In [195]:
np.sum(c,axis=2)

array([[ 6, 22],
       [38, 54],
       [70, 86]])