### The difference between the list and numpy performance

In [2]:
import time
import sys
import numpy as np

In [4]:
start_time = time.time()
l = [i*2 for i in range(100)]
end_time = time.time()
print("The list time is {:f}".format(end_time-start_time))
print('The size of list :',sys.getsizeof(l))

The list time is 0.000189
The size of list : 920


In [12]:
start_time = time.time()
l = np.array([i*2 for i in range(100)])
end_time = time.time()
print("The list time is {:f}".format(end_time-start_time))
print('The size of list :',sys.getsizeof(np))

The list time is 0.000376
The size of list : 72


### Numpy Creation

**1. Numpy creation with list**

In [ ]:
import numpy as np

syntax
-------
arr = np.array(homogeneous.seq)  # sequence are list, tuple, set

In [27]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [21]:
import cv2
cv2.imread('/Users/pranay/Downloads/Pranay Photo/i2.jpg')

array([[[202, 189, 187],
        [202, 189, 187],
        [202, 189, 187],
        ...,
        [237, 221, 222],
        [237, 221, 222],
        [237, 221, 222]],

       [[202, 189, 187],
        [203, 190, 188],
        [203, 190, 188],
        ...,
        [237, 221, 222],
        [237, 221, 222],
        [237, 221, 222]],

       [[203, 190, 188],
        [203, 190, 188],
        [203, 190, 188],
        ...,
        [237, 221, 222],
        [237, 221, 222],
        [237, 221, 222]],

       ...,

       [[146, 148, 212],
        [146, 148, 212],
        [144, 146, 210],
        ...,
        [ 84,  82, 141],
        [ 87,  85, 144],
        [ 89,  87, 146]],

       [[143, 145, 209],
        [142, 144, 208],
        [140, 142, 206],
        ...,
        [ 82,  80, 139],
        [ 85,  83, 142],
        [ 88,  86, 145]],

       [[141, 143, 207],
        [140, 142, 206],
        [139, 141, 205],
        ...,
        [ 82,  80, 139],
        [ 84,  82, 141],
        [ 87,  85, 144]]

In [23]:
!pip install opencv-python

  Using cached numpy-2.2.6-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.2.6-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.6 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.2.6 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.6 which is incompatible.


In [29]:
np.array([7,8,9])

array([7, 8, 9])

In [31]:
np.array([[7,8,9]])

array([[7, 8, 9]])

In [35]:
arr = np.array([[7,8,9],[1,2,3]])
arr.shape

(2, 3)

In [39]:
np.array([
    [
        [1,2,3],[3,2,1]
    ]
]).shape

(1, 2, 3)

In [43]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



**2. Numpy creation with tuple**

In [49]:
np.array((1,2))

array([1, 2])

In [51]:
np.array(((1,2),(3,4)))

array([[1, 2],
       [3, 4]])

**3. Numpy creation with set**

In [55]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [58]:
np.array({{1,2}})

TypeError: unhashable type: 'set'

### Properties of Array

In [60]:
arr.shape

(2, 3)

In [62]:
arr.ndim

2

In [64]:
arr.size

6

In [66]:
arr.dtype

dtype('int64')

In [68]:
arr.nbytes

48

In [70]:
arr.itemsize

8

In [74]:
arr??

Type:        ndarray
String form:
[[7 8 9]
 [1 2 3]]
Length:      2
File:        /opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any o

In [84]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])